# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.6.0
      - image: circleci/mysql:8.0.17
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: urbandiction
          MYSQL_USER: root
          MYSQL_PASSWORD: root

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo apt-get update
      - run: sudo apt-get install mysql-server
      - run: mysql -h 127.0.0.1 -P 3306 -u root -proot urbandiction
      # - run: sudo apt-get install default-mysql-client
      # start the server in the background
      - run: mysql -u root -proot < ./server/db/seed_data.sql
      - run:
          command: node ./server/server.js
          background: true
      # run tests!
      - run: npm test
      - run: npx eslint "**/*.js" --ignore-pattern node_modules/
